source:      .
destination: ./_site
plugins_dir:     ./_plugins
timezone:    Asia/Shanghai

#server:   false
author:   ddrccw
lsi:      false
safe:     false

github_user:  ddrccw
disqus_short_name: ddrccw

#plugin jekyll-pagination at blog.html
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false


permalink: /:year/:month/:day/:title
exclude:   ["Rakefile", "CNAME", "ddrccw.tmproj", "ddrccw.sublime-project", "ddrccw.sublime-workspace"]
title:     ddrccw's library
url:       http://ddrccw.github.io
baseurl:   /
#category_title_prefix
#category_meta_description_prefix

recent_post_listing_limit: 10        #single page only has 10 articles

Links:

    Lontoken: &Lontoken
        title:       Lontoken's Blog
        url:         http://www.lontoken.com/
    pwq1989: &pwq1989
        title:       右席的搬砖日记
        url:         http://www.cppblog.com/pwq1989/

#-----demo--------
#projects:
#    name: &name    //should be unique
#        title:     title
#        category:  study or feature
#        languages: e.g. [Objective C, C++, Ruby] 
#        icon:      project_icon.png                          //optional
#        version:   version_number                            //optional
#        download:  download_url                              //optional
#        docs:      wiki or docs_url                          //optional 
#        changelog: true or false if existing changelog.html  //optional
#        apidocs:   true or false if existing apidocs         //optional
#        support:   support_url                               //optional

projects:

    CCCircleSpinLayer: &CCCircleSpinLayer
        title:        CCCircleSpinLayer
        category:     实战
        languages:    [Objective C]
        description:  >
            Circle spinner referred to SpinKit and SpinKit-ObjC。

    CCScrollableHeaderTabViewController: &CCScrollableHeaderTabViewController
        title:        CCScrollableHeaderTabViewController
        category:     实战
        languages:    [Objective C]
        description:  >
            云课堂，中国大学mooc的课程详情页用到的组件。

    CCTransition: &CCTransition
        title:        CCTransition
        category:     实战
        languages:    [Objective C]
        description:  >
            云课堂，中国大学mooc转场动画组件。

    CCRotation: &CCRotation
        title:        CCRotation
        category:     实战
        languages:    [Objective C]
        description:  >
            基于CoreMotion检测设备方向

    CCChainedMenu: &CCChainedMenu
        title:        CCChainedMenu
        category:     study
        languages:    [Objective C]
        description:  >
            尝试运用CAAnimation, 效果类似UCWeb iPad端右下角的小菜单。

    CCRichTextEditor: &CCRichTextEditor
        title:        CCRichTextEditor
        category:     study
        languages:    [Objective C]
        description:  >
            利用UIWebView实现富文本编辑。尝试obj-c与javascript交互。 使用AudioSession实现录音及播放。

















