source:      .
destination: ./_site
plugins:     ./_plugins

#server:   false
author:   ddrccw
lsi:      false
safe:     false
markdown: rdiscount
#markdown: maruku
pygments: true

github_user:  ddrccw
disqus_short_name: ddrccw

paginate: 5

permalink: /:year/:month/:day/:title
exclude:   ["Rakefile", "CNAME", "ddrccw.tmproj"]
title:     ddrccw's library
url:       http://ddrccw.github.com
