source:      .
destination: ./_site
plugins:     ./_plugins

#server:   false
author:   ddrccw
lsi:      false
safe:     false
markdown: rdiscount
#markdown: maruku
pygments: true

github_user:  ddrccw
disqus_short_name: ddrccw

#plugin jekyll-pagination at blog.html
paginate: 5
paginate_files: 
  - blog.html


permalink: /:year/:month/:day/:title
exclude:   ["Rakefile", "CNAME", "ddrccw.tmproj"]
title:     ddrccw's library
url:       http://ddrccw.github.com

#category_title_prefix
#category_meta_description_prefix

recent_post_listing_limit: 10        #single page only has 10 articles


#-----demo--------
#projects:
#    name: &name    //should be unique
#        title:     title
#        category:  study or feature
#        languages: e.g. [Objective C, C++, Ruby] 
#        icon:      project_icon.png                          //optional
#        version:   version_number                            //optional
#        download:  download_url                              //optional
#        docs:      wiki or docs_url                          //optional 
#        changelog: true or false if existing changelog.html  //optional
#        apidocs:   true or false if existing apidocs         //optional
#        support:   support_url                               //optional

projects:

    CCChainedMenu: &CCChainedMenu
        title:        CCChainedMenu
        category:     study
        languages:    [Objective C]
        description:  >
            尝试运用CAAnimation, 效果类似UCWeb iPad端右下角的小菜单。

    CCRichTextEditor: &CCRichTextEditor
        title:        CCRichTextEditor
        category:     study
        languages:    [Objective C]
        description:  >
            利用UIWebView实现富文本编辑。尝试obj-c与javascript交互。

